# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_speaker',
            field=models.BooleanField(default=False),
        ),
    ]
