# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_myuser_is_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='choice',
            name='vote_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_counter',
            field=models.IntegerField(default=0),
        ),
    ]
